#!/bin/bash

echo "🍓 GainTempsIA - Déploiement sur Raspberry Pi"
echo "=============================================="
echo ""
echo "📝 ÉTAPES À SUIVRE :"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1️⃣  POUSSER SUR GITHUB (sur votre Mac)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "cd /Users/duhaz/projets/gaintemps-ia"
echo "git remote add origin https://github.com/VOTRE-USERNAME/gaintemps-ia.git"
echo "git branch -M main"  
echo "git push -u origin main"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "2️⃣  SUR VOTRE RASPBERRY PI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Mettre à jour le système"
echo "sudo apt update && sudo apt upgrade -y"
echo ""
echo "# Installer Docker"
echo "curl -fsSL https://get.docker.com -o get-docker.sh"
echo "sudo sh get-docker.sh"
echo "sudo usermod -aG docker \$USER"
echo ""
echo "# Redémarrer la session ou le RPi"
echo "sudo reboot"
echo ""
echo "# Après redémarrage, cloner le projet"
echo "git clone https://github.com/VOTRE-USERNAME/gaintemps-ia.git"
echo "cd gaintemps-ia/api"
echo ""
echo "# Configurer l'API"
echo "cp .env.example .env"
echo "nano .env  # Ajoutez votre clé Resend"
echo ""
echo "# Construire et lancer"
echo "docker compose build"
echo "docker compose up -d"
echo ""
echo "# Vérifier que ça marche"
echo "docker compose logs -f"
echo "curl http://localhost:3000/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "3️⃣  TESTER L'API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Depuis un autre ordinateur sur votre réseau :"
echo "curl http://IP-DU-RPI:3000/health"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📖 Documentation complète : cat RASPBERRY-PI.md"
echo ""
echo "💡 Astuces :"
echo "   - La compilation sur RPi prend 5-10 minutes"
echo "   - Raspberry Pi 4 avec 4GB RAM recommandé"
echo "   - L'image Docker est compatible ARM64/ARM32"
echo ""
echo "🎯 Une fois l'API fonctionnelle sur le RPi, vous pourrez :"
echo "   - Installer Caddy pour servir le frontend"
echo "   - Configurer un nom de domaine"
echo "   - Ouvrir les ports sur votre routeur"
echo ""
echo "Bon déploiement ! 🚀"
