#!/bin/bash

echo "🐳 Installation de Docker sur macOS"
echo "===================================="
echo ""
echo "Vous avez 2 options :"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 1 : Docker Desktop (RECOMMANDÉ)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Téléchargez Docker Desktop depuis :"
echo "   https://www.docker.com/products/docker-desktop/"
echo ""
echo "2. Installez l'application (.dmg)"
echo ""
echo "3. Lancez Docker Desktop"
echo ""
echo "4. Attendez que Docker démarre (icône dans la barre de menu)"
echo ""
echo "5. Testez : docker --version"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Option 2 : Via Homebrew"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Installez Homebrew d'abord :"
echo '   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'
echo ""
echo "2. Puis installez Docker :"
echo "   brew install --cask docker"
echo ""
echo "3. Lancez Docker Desktop depuis Applications"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 Une fois Docker installé, revenez et lancez :"
echo "   cd /Users/duhaz/projets/gaintemps-ia/api"
echo "   docker compose build"
echo "   docker compose up -d"
echo ""
echo "📝 Note : Vous êtes sur macOS, donc Docker Desktop est la meilleure option"
echo "         (interface graphique + gestion facile)"
