#!/bin/bash

echo "🚀 GainTempsIA - Prêt pour GitHub!"
echo "===================================="
echo ""
echo "✅ Git initialisé"
echo "✅ Premier commit effectué (19 fichiers, 1908 lignes)"
echo "✅ Configuration Git définie"
echo ""
echo "📝 PROCHAINES ÉTAPES :"
echo ""
echo "1️⃣  Créer le repository sur GitHub"
echo "   → Allez sur https://github.com/new"
echo "   → Nom du repository : gaintemps-ia"
echo "   → Description : Site web et API pour GainTempsIA - Consulting IA pour TPE/PME"
echo "   → Choisissez Public ou Private"
echo "   → Ne cochez PAS 'Initialize with README'"
echo "   → Cliquez 'Create repository'"
echo ""
echo "2️⃣  Lier votre projet local à GitHub"
echo ""
echo "   Copiez ces commandes (remplacez VOTRE-USERNAME par votre vrai username GitHub) :"
echo ""
echo "   cd /Users/duhaz/projets/gaintemps-ia"
echo "   git remote add origin https://github.com/VOTRE-USERNAME/gaintemps-ia.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3️⃣  Vérifier sur GitHub"
echo "   → Allez sur https://github.com/VOTRE-USERNAME/gaintemps-ia"
echo "   → Vous devriez voir tous vos fichiers !"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "💡 ASTUCE : GitHub vous donnera ces commandes exactes après avoir créé le repo"
echo ""
echo "📚 Pour plus d'infos : cat DEPLOIEMENT.md"
echo ""
echo "🎉 Bon courage !"
