version: '3.8'

services:
  gaintemps-ia-api:
    build: .
    container_name: gaintemps-ia-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
      - PORT=3000
      - ALLOWED_ORIGIN=${ALLOWED_ORIGIN}
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - gaintemps-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  gaintemps-network:
    driver: bridge
